spring:
  application:
    name: jogos
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/aula10
    password: root
  jpa:
    hibernate:
      ddl-auto: update