spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      profile: dev
  zipkin:
    base-url: http://zipkin:9411/

eureka:
  instance:
#    prefer-ip-address: true
    hostname: eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/