spring:
  application:
    name: movie
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: dev
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 15672

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/avaliacao_i
    password: root
  jpa:
    hibernate:
      ddl-auto: update

queue:
  movie:
    name: MovieQueue

message: movie up