#server:
#    port: $(PORT:8888)
#
#message: configuracao padrao com spring cloud config!
#
#spring:
##    application:
##        name: ConfigServer
#    cloud:
#        config:
#            server:
#                git:
#                    uri: https://github.com/helenaperdigueiro/especializacao_backend_I