server:
  port: 8001
  servlet:
    context-path: /persona/

spring:
  application:
    name: persona-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/avaliacao_i
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  persona:
    name: PersonaQueue

message: persona up

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: microservicio persona
  svc:
#    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}