server:
  port: 8888

spring:
  application:
    name: config-server
  zipkin:
    base-url: http://zipkin-service:9411/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/helenaperdigueiro/especializacao_backend_I
            default-label: main
            search-paths:
              - 'cloud-config*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/